### ISSUE TITLE
Missing functionality in KJSencha\Controller\DataController

### ISSUE THREAD

**Issue by jaztec** [Rovak/KJSencha#38]
The javascript component KJSencha.data.Factory is able to generate multiple store configurations allowing additional program flows.

However when you analyse the PHP objects, given route kjsencha/data/[:action] the action should be processed in KJSencha\Controller\DataController, only the componentloader seems to has reason to work; it's the only action provided. The routes for 'rest', 'service' and 'polling' are non-existent. RPC requests are ofcourse handled by the DirectController. That is all clear.

Shouldn't these actions be completed as well for the services to work or am I missing something?

**Comment by Rovak** [comment]
Some functions provided in the [KJSencha.data.Factory](https://github.com/Rovak/KJSencha/blob/master/public/js/classes/KJSencha/data/Factory.js) object are remnants of a very early version of the library. This first version provided utility functions to create stores for Rest, Polling and Service datastores. Because these helper functions usually differ between projects i decided to not maintain them anymore. I will remove them in a future update.

**Comment by jaztec** [comment]
Ok thanks! I will use the remnants in my own projects
